In [1]:
import pandas as pd
from pandas.io.json import json_normalize
from numpy import loadtxt
import data_handling as file_dh
import pred_model as file_pred_mdl

cumtd_df = pd.read_csv("Mar30_twilight_WITH_CORR.csv")
# cumtd_df = cumtd_df_temp.drop(["Unnamed: 0", "id"], axis = 1)
cumtd_df

D:\Anaconda\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

,Unnamed: 0,query_time,stop_id,headsign,trip_id,trip_service_id,trip_shape_id,vehicle_id,is_monitored,is_scheduled,...,trip_shape_id_encoded,scheduled_date_only,expected_scheduled_diff,diff_in_sec,time_since_appearance,number_of_stalls,day_of_week,query_weekday_encoded,time_elapsed_since_twelve_AM,corr_expected_min_vs_tsa
0,0,2021-02-22 12:38:01,IU:1,13N Silver,[@12.0.42199629@][3][1246905728609]/13__SV4_MF,SILVER 2,SV4 MF,1185.0,1,1,...,86,2021-02-22,314.0,45.0,0.0,1,Monday,1,45481,0.000000
1,1,2021-02-22 12:38:01,IU:9,13S Silver,[@12.0.42199629@][4][1246896833000]/82__SV2_MF,SILVER 120,SV2 MF,1177.0,1,1,...,85,2021-02-22,44.0,-27.0,0.0,1,Monday,1,45481,0.000000
2,2,2021-02-22 12:38:01,IU:1,8E Bronze,[@7.0.41201636@][3][1243611110703]/3__BZ1_MF,8E,BZ1 MF,1606.0,1,1,...,5,2021-02-22,262.0,-35.0,0.0,1,Monday,1,45481,0.000000
3,3,2021-02-22 12:38:01,IU:9,22S Illini,[@7.0.41200832@][2][1238430887312]/167__I4_UIMF,[@15.0.68513188@]4,I4 UIMF,2020.0,1,1,...,53,2021-02-22,88.0,-71.0,0.0,1,Monday,1,45481,0.000000
4,4,2021-02-22 12:38:01,IU:1,2U Red,[@14.0.56288404@][2][1302789028390]/9__R2_MF,RED 6,R2 MF,1194.0,1,1,...,72,2021-02-22,343.0,-14.0,0.0,1,Monday,1,45481,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1281606,1281606,2021-03-03 15:10:04,WLNTLGN:1,5W Green,5GN569__GN5_MF,5W-PM,GN5 MF,1603.0,1,1,...,25,2021-03-03,197.0,-978.0,902.0,1,Wednesday,6,54604,-0.992169
1281607,1281607,2021-03-03 15:10:04,WLNTLGN:2,5W Green Hopper,[@7.0.41101146@][4][1237930167062]/28__GN8_MF,5W HOPPER 81,GN8 MF,1163.0,1,1,...,29,2021-03-03,94.0,-1572.0,301.0,1,Wednesday,6,54604,-0.827978
1281608,1281608,2021-03-03 15:10:04,WLNTLGN:1,6W Orange,[@2.0.86175868@][1458585713139]/51__O3_MF,[@2.0.86175868@]25,O3 MF,1717.0,1,1,...,67,2021-03-03,0.0,-1612.0,179.0,2,Wednesday,6,54604,-0.917053
1281609,1281609,2021-03-03 15:10:04,WLNTLGN:1,5W Green Hopper,[@7.0.41101146@][4][1237930167062]/28__GN8_MF,5W HOPPER 81,GN8 MF,1163.0,1,1,...,29,2021-03-03,94.0,-1762.0,120.0,1,Wednesday,6,54604,-0.512551
1281610,1281610,2021-03-03 15:10:04,WLNTLGN:1,9B Brown,[@2.0.80548152@][12][1425572286750]/26__BB2_MF,[@15.0.61662606@]366,BB2 MF,1610.0,1,1,...,4,2021-03-03,115.0,-1795.0,0.0,1,Wednesday,6,54604,0.000000

In [2]:
cumtd_df_subset = cumtd_df.head(100000)
cumtd_df_subset

,Unnamed: 0,query_time,stop_id,headsign,trip_id,trip_service_id,trip_shape_id,vehicle_id,is_monitored,is_scheduled,...,trip_shape_id_encoded,scheduled_date_only,expected_scheduled_diff,diff_in_sec,time_since_appearance,number_of_stalls,day_of_week,query_weekday_encoded,time_elapsed_since_twelve_AM,corr_expected_min_vs_tsa
0,0,2021-02-22 12:38:01,IU:1,13N Silver,[@12.0.42199629@][3][1246905728609]/13__SV4_MF,SILVER 2,SV4 MF,1185.0,1,1,...,86,2021-02-22,314.0,45.0,0.0,1,Monday,1,45481,0.000000
1,1,2021-02-22 12:38:01,IU:9,13S Silver,[@12.0.42199629@][4][1246896833000]/82__SV2_MF,SILVER 120,SV2 MF,1177.0,1,1,...,85,2021-02-22,44.0,-27.0,0.0,1,Monday,1,45481,0.000000
2,2,2021-02-22 12:38:01,IU:1,8E Bronze,[@7.0.41201636@][3][1243611110703]/3__BZ1_MF,8E,BZ1 MF,1606.0,1,1,...,5,2021-02-22,262.0,-35.0,0.0,1,Monday,1,45481,0.000000
3,3,2021-02-22 12:38:01,IU:9,22S Illini,[@7.0.41200832@][2][1238430887312]/167__I4_UIMF,[@15.0.68513188@]4,I4 UIMF,2020.0,1,1,...,53,2021-02-22,88.0,-71.0,0.0,1,Monday,1,45481,0.000000
4,4,2021-02-22 12:38:01,IU:1,2U Red,[@14.0.56288404@][2][1302789028390]/9__R2_MF,RED 6,R2 MF,1194.0,1,1,...,72,2021-02-22,343.0,-14.0,0.0,1,Monday,1,45481,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,2021-02-23 07:00:04,WHT2ND:1,12W Teal,[@7.0.41893871@][4][1243540790859]/1__T1_MF,12W TEAL 12,T1 MF,1603.0,1,1,...,87,2021-02-23,0.0,-101.0,301.0,3,Tuesday,5,25204,-0.999869
99996,99996,2021-02-23 07:00:04,WHT2ND:3,12E Teal Orchard Downs,[@7.0.41893871@][3][1243541396687]/71__T1_MF,12E TEAL 13,T1 MF,1603.0,1,1,...,87,2021-02-23,0.0,130.0,2.0,2,Tuesday,5,25204,0.000000
99997,99997,2021-02-23 07:00:05,WLNTLGN:1,9B Brown,[@2.0.80548152@][12][1430505742107]/0__BB2_MF,[@15.0.61662606@]690,BB2 MF,2044.0,1,1,...,4,2021-02-23,-11.0,57.0,962.0,3,Tuesday,5,25205,-0.996136
99998,99998,2021-02-23 07:00:05,WLNTLGN:1,7W Grey,[@2.0.80545657@][32][1425491542774]/0__GR3_MF,7W,GR3 MF,1724.0,1,1,...,41,2021-02-23,37.0,-37.0,784.0,2,Tuesday,5,25205,-0.986414
99999,99999,2021-02-23 07:00:05,WLNTLGN:1,2C Red,[@14.0.56288404@][41][1316446361177]/2__GN8_MF,[@14.0.56288404@]40,GN8 MF,1188.0,1,1,...,29,2021-02-23,98.0,5.0,360.0,1,Tuesday,5,25205,-0.884229

In [3]:
cumtd_df_subset = file_dh.rolling_correlations(cumtd_df_subset, "expected_mins", "time_since_appearance")
cumtd_df_subset

d:\UIUC MISM Studies\2021 Spring\Independent Study\uiuc_msim_indie_study-master\data_handling.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_dataframe[new_feature_name] = -2
D:\Anaconda\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
d:\UIUC MISM Studies\2021 Spring\Independent Study\uiuc_msim_indie_study-master\data_handling.py:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_dataframe[new_feature_name] = clean_dataframe[new_feature_name].fillna(-2)

,Unnamed: 0,query_time,stop_id,headsign,trip_id,trip_service_id,trip_shape_id,vehicle_id,is_monitored,is_scheduled,...,scheduled_date_only,expected_scheduled_diff,diff_in_sec,time_since_appearance,number_of_stalls,day_of_week,query_weekday_encoded,time_elapsed_since_twelve_AM,corr_expected_min_vs_tsa,corr_expected_mins_vs_time_since_appearance
0,0,2021-02-22 12:38:01,IU:1,13N Silver,[@12.0.42199629@][3][1246905728609]/13__SV4_MF,SILVER 2,SV4 MF,1185.0,1,1,...,2021-02-22,314.0,45.0,0.0,1,Monday,1,45481,0.000000,-2.000000
1,1,2021-02-22 12:38:01,IU:9,13S Silver,[@12.0.42199629@][4][1246896833000]/82__SV2_MF,SILVER 120,SV2 MF,1177.0,1,1,...,2021-02-22,44.0,-27.0,0.0,1,Monday,1,45481,0.000000,-2.000000
2,2,2021-02-22 12:38:01,IU:1,8E Bronze,[@7.0.41201636@][3][1243611110703]/3__BZ1_MF,8E,BZ1 MF,1606.0,1,1,...,2021-02-22,262.0,-35.0,0.0,1,Monday,1,45481,0.000000,-2.000000
3,3,2021-02-22 12:38:01,IU:9,22S Illini,[@7.0.41200832@][2][1238430887312]/167__I4_UIMF,[@15.0.68513188@]4,I4 UIMF,2020.0,1,1,...,2021-02-22,88.0,-71.0,0.0,1,Monday,1,45481,0.000000,-2.000000
4,4,2021-02-22 12:38:01,IU:1,2U Red,[@14.0.56288404@][2][1302789028390]/9__R2_MF,RED 6,R2 MF,1194.0,1,1,...,2021-02-22,343.0,-14.0,0.0,1,Monday,1,45481,0.000000,-2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,2021-02-23 07:00:04,WHT2ND:1,12W Teal,[@7.0.41893871@][4][1243540790859]/1__T1_MF,12W TEAL 12,T1 MF,1603.0,1,1,...,2021-02-23,0.0,-101.0,301.0,3,Tuesday,5,25204,-0.999869,-0.999869
99996,99996,2021-02-23 07:00:04,WHT2ND:3,12E Teal Orchard Downs,[@7.0.41893871@][3][1243541396687]/71__T1_MF,12E TEAL 13,T1 MF,1603.0,1,1,...,2021-02-23,0.0,130.0,2.0,2,Tuesday,5,25204,0.000000,-2.000000
99997,99997,2021-02-23 07:00:05,WLNTLGN:1,9B Brown,[@2.0.80548152@][12][1430505742107]/0__BB2_MF,[@15.0.61662606@]690,BB2 MF,2044.0,1,1,...,2021-02-23,-11.0,57.0,962.0,3,Tuesday,5,25205,-0.996136,-0.996136
99998,99998,2021-02-23 07:00:05,WLNTLGN:1,7W Grey,[@2.0.80545657@][32][1425491542774]/0__GR3_MF,7W,GR3 MF,1724.0,1,1,...,2021-02-23,37.0,-37.0,784.0,2,Tuesday,5,25205,-0.986414,-0.986414
99999,99999,2021-02-23 07:00:05,WLNTLGN:1,2C Red,[@14.0.56288404@][41][1316446361177]/2__GN8_MF,[@14.0.56288404@]40,GN8 MF,1188.0,1,1,...,2021-02-23,98.0,5.0,360.0,1,Tuesday,5,25205,-0.884229,-0.884229

In [4]:
cumtd_df_subset.columns

Index(['Unnamed: 0', 'query_time', 'stop_id', 'headsign', 'trip_id',
       'trip_service_id', 'trip_shape_id', 'vehicle_id', 'is_monitored',
       'is_scheduled', 'is_istop', 'scheduled', 'expected', 'expected_mins',
       'location_lat', 'location_long', 'is_departed', 'actual',
       'stop_id_stem', 'stop_id_encoded', 'headsign_encoded',
       'trip_shape_id_encoded', 'scheduled_date_only',
       'expected_scheduled_diff', 'diff_in_sec', 'time_since_appearance',
       'number_of_stalls', 'day_of_week', 'query_weekday_encoded',
       'time_elapsed_since_twelve_AM', 'corr_expected_min_vs_tsa',
       'corr_expected_mins_vs_time_since_appearance'],
      dtype='object')

In [5]:
cumtd_df_subset = file_dh.obtain_avg_lateness_by_group(cumtd_df_subset, "vehicle_id")
cumtd_df_subset

d:\UIUC MISM Studies\2021 Spring\Independent Study\uiuc_msim_indie_study-master\data_handling.py:128: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_dataframe[new_feature_name] = -10000
D:\Anaconda\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,Unnamed: 0,query_time,stop_id,headsign,trip_id,trip_service_id,trip_shape_id,vehicle_id,is_monitored,is_scheduled,...,expected_scheduled_diff,diff_in_sec,time_since_appearance,number_of_stalls,day_of_week,query_weekday_encoded,time_elapsed_since_twelve_AM,corr_expected_min_vs_tsa,corr_expected_mins_vs_time_since_appearance,avg_lateness_by_vehicle_id
0,0,2021-02-22 12:38:01,IU:1,13N Silver,[@12.0.42199629@][3][1246905728609]/13__SV4_MF,SILVER 2,SV4 MF,1185.0,1,1,...,314.0,45.0,0.0,1,Monday,1,45481,0.000000,-2.000000,45.00
1,1,2021-02-22 12:38:01,IU:9,13S Silver,[@12.0.42199629@][4][1246896833000]/82__SV2_MF,SILVER 120,SV2 MF,1177.0,1,1,...,44.0,-27.0,0.0,1,Monday,1,45481,0.000000,-2.000000,-27.00
2,2,2021-02-22 12:38:01,IU:1,8E Bronze,[@7.0.41201636@][3][1243611110703]/3__BZ1_MF,8E,BZ1 MF,1606.0,1,1,...,262.0,-35.0,0.0,1,Monday,1,45481,0.000000,-2.000000,-35.00
3,3,2021-02-22 12:38:01,IU:9,22S Illini,[@7.0.41200832@][2][1238430887312]/167__I4_UIMF,[@15.0.68513188@]4,I4 UIMF,2020.0,1,1,...,88.0,-71.0,0.0,1,Monday,1,45481,0.000000,-2.000000,-71.00
4,4,2021-02-22 12:38:01,IU:1,2U Red,[@14.0.56288404@][2][1302789028390]/9__R2_MF,RED 6,R2 MF,1194.0,1,1,...,343.0,-14.0,0.0,1,Monday,1,45481,0.000000,-2.000000,-14.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,2021-02-23 07:00:04,WHT2ND:1,12W Teal,[@7.0.41893871@][4][1243540790859]/1__T1_MF,12W TEAL 12,T1 MF,1603.0,1,1,...,0.0,-101.0,301.0,3,Tuesday,5,25204,-0.999869,-0.999869,-17.02
99996,99996,2021-02-23 07:00:04,WHT2ND:3,12E Teal Orchard Downs,[@7.0.41893871@][3][1243541396687]/71__T1_MF,12E TEAL 13,T1 MF,1603.0,1,1,...,0.0,130.0,2.0,2,Tuesday,5,25204,0.000000,-2.000000,-15.84
99997,99997,2021-02-23 07:00:05,WLNTLGN:1,9B Brown,[@2.0.80548152@][12][1430505742107]/0__BB2_MF,[@15.0.61662606@]690,BB2 MF,2044.0,1,1,...,-11.0,57.0,962.0,3,Tuesday,5,25205,-0.996136,-0.996136,15.96
99998,99998,2021-02-23 07:00:05,WLNTLGN:1,7W Grey,[@2.0.80545657@][32][1425491542774]/0__GR3_MF,7W,GR3 MF,1724.0,1,1,...,37.0,-37.0,784.0,2,Tuesday,5,25205,-0.986414,-0.986414,-72.86
99999,99999,2021-02-23 07:00:05,WLNTLGN:1,2C Red,[@14.0.56288404@][41][1316446361177]/2__GN8_MF,[@14.0.56288404@]40,GN8 MF,1188.0,1,1,...,98.0,5.0,360.0,1,Tuesday,5,25205,-0.884229,-0.884229,87.41